### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by mmousaei** [castacks/PX4-fully-actuated#20]

**Comment by lygoon** [comment]
Dear sir, I encountered some problems related to simulation and off-board flight mode during the test.
(1) The first problem: When I use the firmware simulation, the terminal will always appear the following warning after using the game handle to switch the flight mode to the position mode:
***************************************************************(dividing line)
[ WARN] [1677655764.650572529, 52.504000000]: PositionTargetGlobal failed because no origin
***************************************************************(dividing line)
How can I solve it?
(2) The second problem: Although there will be a warning when switching to the position mode, you can still use the handle to control the flight. However, when I switch to the off-board mode with the handle, the UAV in the gazebo will get stuck, and the terminal will have the following error:
***************************************************************(dividing line)
ERROR [sensors] Accel #0 fail:  TIMEOUT!
ERROR [sensors] Sensor Accel #0 failed.  Reconfiguring sensor priorities.
WARN  [sensors] Remaining sensors after failover event 0: Accel #0 priority: 1
ERROR [sensors] Gyro #0 fail:  TIMEOUT!
ERROR [sensors] Sensor Gyro #0 failed.  Reconfiguring sensor priorities.
WARN  [sensors] Remaining sensors after failover event 0: Gyro #0 priority: 1
[ERROR] [1677655768.730524811, 56.524000000]: FCU: Accel #0 fail:  TIMEOUT!
[ERROR] [1677655768.780698976, 56.524000000]: FCU: Gyro #0 fail:  TIMEOUT!
ERROR [sensors] Mag #0 fail:  TIMEOUT!
ERROR [sensors] Sensor Mag #0 failed.  Reconfiguring sensor priorities.
WARN  [sensors] Remaining sensors after failover event 0: Mag #0 priority: 1
[ERROR] [1677655768.980502271, 56.524000000]: FCU: Mag #0 fail:  TIMEOUT!
ERROR [mavlink] [timesync] Time jump detected.  Resetting time synchroniser.
[ERROR] [1677655769.356481254, 56.524000000]: TM : Time jump detected.  Resetting time synchroniser.
WARN  [commander] Failsafe enabled: no offboard
[ERROR] [1677655774.206670232, 56.524000000]: FCU: Failsafe enabled: no offboard
****************************************************************(dividing line)
Therefore, I don't know whether it is the firmware problem or whether I use group in the off-board mode_ The format of force and moment sent by mix is incorrect. I wrote this:
*****************************************************************(dividing line)
mixerControl.group_ mix = 0;
mixerControl.controls[0] = std::max(-0.3, std::min(0.3, geometry_control.torque(0)));// roll torque
mixerControl.controls[1] = std::max(-0.3, std::min(0.3, -geometry_control.torque(1)));// pitch torque
mixerControl.controls[2] = std::max(-0.3, std::min(0.3, -geometry_control.torque(2)));// yaw torch
mixerControl.controls[3] = std::max(0.0, std::min(0.95, 0.05*(geometry_control.thrustAct(0)+0.567)));
mixerControl.controls[4] = std::max(0.0, std::min(0.95, 0.05*(geometry_control.thrustAct(1)+0.567)));
mixerControl.controls[5] = std::max(0.0, std::min(0.95, 0.05*(geometry_control.thrustAct(2)-geometry_ control.mass*geometry_ control.gravity)+0.567));
mixerControl.controls[6] = 0.0;
mixerControl.controls[7] = 0.0;
****************************************************************(dividing line)
Is there any mistake in the format and method of sending force and torque? And how to solve this error?
These questions have troubled me for some time. I hope to get your answer. thank you!
