### ISSUE TITLE
where is the thrust setpoint generator?

### ISSUE THREAD

**Issue by Lokleee** [castacks/PX4-fully-actuated#22]
I know the paper you write two thrust strategies for fully-actuated uavs. Did you use the strategy of **keeping the Desired Vertical Thrust** or **keeping the acceleration directions**? Where can I find the code? Really need help, please.

**Comment by keipour** [comment]
Thank you for your interest in the code. It has been a while since we touched this code, but if I remember correctly, the vertical thrust and keeping acceleration direction were coded in the simulator but not on this PX4 repo as we did not need them at the time for our experiments.
Please feel free to reach out with any questions if you decide to implement them yourself :)
